name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          python -m pip install --upgrade pip
          pip install cython
          pip install --upgrade buildozer

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android SDK and NDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
          unzip commandlinetools-linux-8092744_latest.zip -d android-sdk
          echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
          echo "$PWD/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.1.8937393"
          echo "ANDROID_NDK_HOME=$PWD/android-sdk/ndk/25.1.8937393" >> $GITHUB_ENV

      - name: Accept Android SDK Licenses
        run: |
          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses

      - name: Update Buildozer.spec
        run: |
          sed -i 's|^android.sdk_path =.*|android.sdk_path = '$ANDROID_HOME'|' buildozer.spec
          sed -i 's|^android.ndk_path =.*|android.ndk_path = '$ANDROID_NDK_HOME'|' buildozer.spec
          sed -i 's|^android.api =.*|android.api = 33|' buildozer.spec
          sed -i 's|^android.ndk =.*|android.ndk = 25.1.8937393|' buildozer.spec
          sed -i 's|^android.sdk =.*|#android.sdk = 33|' buildozer.spec

      - name: Clear Buildozer cache
        run: |
          rm -rf ~/.buildozer
          rm -rf .buildozer
          rm -rf bin

      - name: Build with Buildozer
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
