name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install --upgrade buildozer

      - name: Install Android SDK and NDK
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.1.8937393" "tools"
          export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/31.0.0:$ANDROID_HOME/tools/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          
      - name: Set up local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_HOME/ndk/25.1.8937393" >> local.properties

      - name: Verify aidl installation
        run: |
          echo "Verifying aidl tool installation..."
          echo "PATH is: $PATH"
          which aidl

      - name: Build with Buildozer
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
