name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython  # Install Cython
          pip install buildozer

      - name: Install Android SDK and NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          unzip -d $ANDROID_HOME/cmdline-tools commandlinetools-linux-6609375_latest.zip
          yes | $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_HOME/ndk/21.4.7075529" >> local.properties

      - name: Build with Buildozer
        run: buildozer android debug
